[package]
name = "advent2018"
version = "0.1.0"
authors = ["Rob Williams <contact@robwilliams.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.7"
tokio = "0.2.22"